//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36365
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorageModel {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StorageModel.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canned.
        /// </summary>
        internal static string CANNED_STOREAGE {
            get {
                return ResourceManager.GetString("CANNED_STOREAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispatcher: {0} of {1} is dispatched.
        /// </summary>
        internal static string DISPATCHER_DISPATCHED {
            get {
                return ResourceManager.GetString("DISPATCHER_DISPATCHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispatcher: {0} cannnot be dispatched, not enough on stock.
        /// </summary>
        internal static string DISPATCHER_ERROR_NOTONSTOCK {
            get {
                return ResourceManager.GetString("DISPATCHER_ERROR_NOTONSTOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispatcher: {0} cannnot be dispatched, perished.
        /// </summary>
        internal static string DISPATCHER_PERISHED {
            get {
                return ResourceManager.GetString("DISPATCHER_PERISHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perishable.
        /// </summary>
        internal static string PERISHABLE_STOREAGE {
            get {
                return ResourceManager.GetString("PERISHABLE_STOREAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perishable storeage: {0} piece of {1} is expired, removing from storage.
        /// </summary>
        internal static string PERISHABLE_STOREAGE_EXPIRED {
            get {
                return ResourceManager.GetString("PERISHABLE_STOREAGE_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} storeage: {1} piece of {2} is stored, capacity left: {3}.
        /// </summary>
        internal static string STORE_REPORT_QUANTITY {
            get {
                return ResourceManager.GetString("STORE_REPORT_QUANTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} storeage: {1} piece of {2} cannnot be stored.
        /// </summary>
        internal static string STOREAGE_ERROR_CANNOT_STORE {
            get {
                return ResourceManager.GetString("STOREAGE_ERROR_CANNOT_STORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} storeage: {1} piece of {2} is put into the storage, capacity left: {3}.
        /// </summary>
        internal static string STOREAGE_STORED {
            get {
                return ResourceManager.GetString("STOREAGE_STORED", resourceCulture);
            }
        }
    }
}
