name: Continuous Integration and Deployment

on:
  push:
    barnches:
      - main
      - dev

jobs:
  build:
  runs-on: ubuntu-latest
  steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ''