name: .NET Core Build & Deployment

on:
  push:
    branches: [ main, dev]
  pull_request:
    branches: [ main, dev]
  schedule:
  - cron: "0 2 * * 1-5"

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./evoFlix
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1
    
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{env.working-directory}}
      
    - name: Build
      run: dotnet build --no-restore
      working-directory: ${{env.working-directory}}
      
    - name: Jira Integration
      if: ${{ always() }}
      uses: rohit-gohri/jira-ci-cd-integration@v0
      with:
        state: ${{ job.status }}
        jira_instance: EFLIX
        client_id: ${{ secrets.JIRA_CLIENT_ID }}
        client_secret: ${{ secrets.JIRA_CLIENT_SECRET }}
